language: rust

rust: stable

before_script:
  - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu # Install cargo-fmt
script: make ci

cache:
  cargo: true

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

notifications:
  email:
    on_success: never
