language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add rustfmt-preview

cache:
  cargo: true

script: make ci

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    on_success: never
