language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add rustfmt --toolchain stable-x86_64-unknown-linux-gnu # Install cargo-fmt
script: make ci

cache:
  cargo: true

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    on_success: never
